apiVersion: v1
data:
  APP_NAME: "trUSt"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://trust.tm.com.my"
  LOG_CHANNEL: stack
  DB_CONNECTION: mysql
  DB_HOST: "172.20.17.181"
  DB_PORT: "3306"
  DB_DATABASE: trust
  DB_USERNAME: trust_app
  DB_PASSWORD: Pswd2018
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: database
  SESSION_LIFETIME: "120"
  MAIL_DRIVER: smtp
  MAIL_HOST: "smtp.tm.com.my"
  MAIL_PORT: "25"
  API_PREFIX: api
  API_DEBUG: "false"
  API_VERSION: "v1"
  API_DEFAULT_FORMAT: json
  API_NAME: "trUSt"
  API_AUTHOR: "D"
  API_STANDARDS_TREE: vnd
  API_SUBTYPE: trust
  TMLDAP_HOSTNAME: "ldaps://idssldap.tm.com.my:636"
  TMLDAP_ADMINUSER: novabillviewerldapadmin
  TMLDAP_ADMINPASS: nHQUbG9Z
  TMOIP_TOKEN: "Bearer 31b8600e-1e25-3c11-ae96-3b5e7ac5ba43"
  TRUST_RESERVE_DUR: "5"
  ERA_API_KEY: "84vlgG7MJO8jHGycAoXl4IFbpvpE6G5YBWAhu4ub"
  ERA_API_URI: "https://g1.iot.tmrnd.com.my"
  GA_KEY: "G-F7SZ6P7TBT"
kind: ConfigMap
metadata:
  name: trustenvprd
